export const drugUseRows = [
  { name: "Cannabis", prescribed: true },
  { name: "Cocaine", prescribed: false },
  { name: "MDMA", prescribed: false },
  { name: "Amphetamine", prescribed: true },
  { name: "Methamphetamine", prescribed: false },
  { name: "Ketamine", prescribed: true },
  { name: "Heroin (Diamorphine)", prescribed: true },
  { name: "Codeine", prescribed: true },
  { name: "Dihydrocodeine", prescribed: true },
  { name: "Morphine", prescribed: true },
  { name: "Diazepam", prescribed: true },
  { name: "Amitriptyline", prescribed: true },
  { name: "Pregabalin", prescribed: true },
  { name: "Gabapentin", prescribed: true },
  { name: "Buprenorphine", prescribed: true },
  { name: "Methadone", prescribed: true },
  { name: "Tramadol", prescribed: true },
];
