export const drugUseRows = [
  { name: "Cannabis", prescribed: true },
  { name: "Cocaine", prescribed: false },
  { name: "Crack Cocaine", prescribed: false },
  { name: "MDMA", prescribed: false },
  { name: "Amphetamine (including certain medications e.g. Elvanse, Lisdexamphetamine/Dexamphetamine)", prescribed: true },
  { name: "Methamphetamine", prescribed: false },
  { name: "Ketamine", prescribed: true },
  { name: "Heroin (Diamorphine - pharmaceutical grade heroin)", prescribed: true },
  { name: "Codeine", prescribed: true },
  { name: "Dihydrocodeine", prescribed: true },
  { name: "Morphine", prescribed: true },
  { name: "Oxycodone (including oxymorphone)", prescribed: true }, 
  { name: "Diazepam (including nordiazepam)", prescribed: true },
  { name: "Other Benzodiazepines (please specify below)", prescribed: true },
  { name: "Amitriptyline", prescribed: true },
  { name: "Pregabalin", prescribed: true },
  { name: "Gabapentin", prescribed: true },
  { name: "Buprenorphine", prescribed: true },
  { name: "Methadone", prescribed: true },
  { name: "Tramadol", prescribed: true },
];
