export const drugExposureRows = [
  "Cannabis",
  "Cocaine",
  "Crack Cocaine",
  "MDMA",
  "Amphetamine",
  "Methamphetamine",
  "Ketamine",
  "Heroin",
  "Codeine",
  "Dihydrocodeine",
  "Morphine",
  "Oxycodone (including oxymorphone)",
  "Diazepam (including nordiazepam)",
  "Other Benzodiazepines (please specify below)",
  "Amitriptyline",
  "Pregabalin",
  "Gabapentin",
  "Buprenorphine",
  "Methadone",
  "Tramadol",
];
